### ISSUE TITLE
Default port for urb

### ISSUE THREAD

**Issue by craigmbooth** [urbit/urb#1]
First-time user, so the misunderstanding may be on my part, but after pulling down the most recent version of urbit into a CentOS 7 VM, urb does not work, giving "connection refused" errors.

Upon inspection, urb is configured to interact on port 12322, whereas when I start up Urbit it is on a different port, reporting the following (confirmed with lsof):

`
http: live (insecure, loopback) on 12321
`

Changing the port in urb makes it work, but I'm hesitating from making a pull request because I'm not 100% sure that I've not just configured things weirdly.  That said, I can't find a reference to port 12322 in the Urbit source tree, but 12321 is in there:

https://github.com/urbit/urbit/blob/e8ab61be7fd7d8d67dd7c449bcd11262b6579a40/vere/http.c#L1103

**Comment by cgyarvin** [comment]
The urb creator is somewhere in the wilds of Iceland.  We've sent out polar commandos, on sleds, to search for him.  Will forward any report.

**Comment by philipcmonk** [comment]
Some polar commandos texted me about this. Sorry, that got incorrectly
pushed in with other changes. Go ahead and PR it!

**Comment by philipcmonk** [comment]
Fixed in #2.
